name: Trigger AWS EC2 Run

on:
  workflow_dispatch:

jobs:
  trigger-run:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS EC2 and run Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}               # e.g. 3.111.222.333
          username: ec2-user                           # Default for Amazon Linux
          key: ${{ secrets.AWS_SSH_KEY }}              # Full private key content
          script_stop: true                            # Stop on any command failure
          timeout: 120s                                # Optional: Increase if needed
          script: |
            set -e
            cd /home/ec2-user/your-project-folder
            git pull origin main                       # Specify branch explicitly
            docker build -t postman-reporter .
            docker run --rm \
              -e API_KEY="${{ secrets.POSTMAN_API_KEY }}" \
              -e COLLECTION_ID="35402997-88acb0d1-f3f8-442b-9180-153e86e70b50" \
              -e ENVIRONMENT_ID="35402997-7363e33e-b323-4dc3-b0ce-daddf1bbfbe1" \
              -e TOKEN_GITHUB="${{ secrets.TOKEN_GITHUB }}" \
              -e REPO="${{ github.repository }}" \
              -e ITERATION_COUNT=1 \
              -e REPORT_FILE="index.html" \
              postman-reporter
