name: Trigger AWS EC2 Run

on:
  workflow_dispatch:

jobs:
  trigger-run:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS and run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ec2-user/your-project-folder
            git pull
            docker build -t postman-reporter .
            docker run --rm \
              -e API_KEY="${{ secrets.POSTMAN_API_KEY }}" \
              -e COLLECTION_ID="..." \
              -e ENVIRONMENT_ID="..." \
              -e TOKEN_GITHUB="${{ secrets.TOKEN_GITHUB }}" \
              -e REPO="${{ github.repository }}" \
              -e ITERATION_COUNT=3 \
              -e REPORT_FILE="index.html" \
              postman-reporter
